--- 
filesystem: 
  mount: /mnt/mysql
lvm: 
  prefix_database: blanketdb-active
  volume_group: !str 
    str: DEFAULT
    "@background": 9
    "@mode": 0
    "@uncolorized": !str 
      str: DEFAULT
      "@background": 9
      "@mode": 0
  prefix_backup: blanketdb-backup
mysql: 
  password: Republic01
  hostname: localhost
  username: root
